name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Buildozer Action
        uses: ArtemisGis/buildozer-action@v1
        with:
          repository_txt: 'main.py'
          buildozer_version: 'stable'

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk